<meta http-equiv="content-type" content="text/html;charset=utf-8">
<h1>增加投票选项</h1>
<form method="post" action="/votesystem/public/admin/add">
    <table>
        <tr><td>名称</td><td><input type="text" name="name"/></td></tr>
        <tr><td>描述</td><td><textarea rows="5" cols="30" name="description"></textarea></td></tr>
        <tr><td>初始投票数</td><td><input type="text" name="vote_count"/></td></tr>
        <tr><td><input type="submit" value="增加"/></td><td><input type="reset" value="重新填写"></td></tr>
    </table>
</form>